param(
    [Parameter(Mandatory = $true)]
    [string] $GeneratedNamespaceFile,
    [Parameter(Mandatory = $true)]
    [string] $OutputFile
)

$ErrorActionPreference = 'Stop'
$source = Get-Content -LiteralPath $GeneratedNamespaceFile -Raw
$pattern = '(?s)(// AA80E7F7-2021-11D2-93E0-0060B067B86E\r?\nvar IID_ITfTextInputProcessor = .*?)(?=\r?\n// 6E4E2102-F9CD-433D-B496-303CE03A6507)'
$match = [regex]::Match($source, $pattern)
if (-not $match.Success) {
    throw 'Could not locate the expected ITfTextInputProcessor declaration block.'
}

$header = @'
// Code generated by Extract-Minimal.ps1; DO NOT EDIT.
// Source generator: zzl/go-winapi-gen commit 4fd990193d56c9ea8fb18ece1adac5016c7dcbc4.
// This is a compile fixture, not an approved production binding.
package tsfdecl

import (
    "syscall"
    "unsafe"

    "github.com/zzl/go-win32api/v2/win32"
)

type HRESULT = win32.HRESULT
type IUnknown = win32.IUnknown
type IUnknownVtbl = win32.IUnknownVtbl
type IUnknownInterface = win32.IUnknownInterface

// ITfThreadMgr is an opaque pointer target for this signature-only fixture.
// It deliberately does not alias IUnknown: the actual interface declaration
// and its methods are outside this first processor-only proof.
type ITfThreadMgr struct {
    IUnknown
}

'@
$declaration = $match.Groups[1].Value
# go vet rejects the generator's unkeyed syscall.GUID literal. Normalize only
# this ABI-equivalent literal shape; the IID fields and bytes remain unchanged.
$declaration = [regex]::Replace(
    $declaration,
    'syscall\.GUID\{(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+),\s*\[8\]byte\{([^}]+)\}\}',
    'syscall.GUID{Data1: $1, Data2: $2, Data3: $3, Data4: [8]byte{$4}}'
)
$content = $header + $declaration + "`r`n"
$content | Set-Content -LiteralPath $OutputFile -Encoding utf8NoBOM
Write-Output "Extracted ITfTextInputProcessor declaration block to $OutputFile"