// Code generated by Extract-Minimal.ps1; DO NOT EDIT.
// Source generator: zzl/go-winapi-gen commit 4fd990193d56c9ea8fb18ece1adac5016c7dcbc4.
// This is a compile fixture, not an approved production binding.
package tsfdecl

import (
	"syscall"
	"unsafe"

	"github.com/zzl/go-win32api/v2/win32"
)

type HRESULT = win32.HRESULT
type IUnknown = win32.IUnknown
type IUnknownVtbl = win32.IUnknownVtbl
type IUnknownInterface = win32.IUnknownInterface

// ITfThreadMgr is an opaque pointer target for this signature-only fixture.
// It deliberately does not alias IUnknown: the actual interface declaration
// and its methods are outside this first processor-only proof.
type ITfThreadMgr struct {
	IUnknown
}

// AA80E7F7-2021-11D2-93E0-0060B067B86E
var IID_ITfTextInputProcessor = syscall.GUID{Data1: 0xAA80E7F7, Data2: 0x2021, Data3: 0x11D2, Data4: [8]byte{0x93, 0xE0, 0x00, 0x60, 0xB0, 0x67, 0xB8, 0x6E}}

type ITfTextInputProcessorInterface interface {
	IUnknownInterface
	Activate(ptim *ITfThreadMgr, tid uint32) HRESULT
	Deactivate() HRESULT
}

type ITfTextInputProcessorVtbl struct {
	IUnknownVtbl
	Activate   uintptr
	Deactivate uintptr
}

type ITfTextInputProcessor struct {
	IUnknown
}

func (this *ITfTextInputProcessor) Vtbl() *ITfTextInputProcessorVtbl {
	return (*ITfTextInputProcessorVtbl)(unsafe.Pointer(this.IUnknown.LpVtbl))
}

func (this *ITfTextInputProcessor) Activate(ptim *ITfThreadMgr, tid uint32) HRESULT {
	ret, _, _ := syscall.SyscallN(this.Vtbl().Activate, uintptr(unsafe.Pointer(this)), uintptr(unsafe.Pointer(ptim)), uintptr(tid))
	return HRESULT(ret)
}

func (this *ITfTextInputProcessor) Deactivate() HRESULT {
	ret, _, _ := syscall.SyscallN(this.Vtbl().Deactivate, uintptr(unsafe.Pointer(this)))
	return HRESULT(ret)
}
