// Code generated by closure-extract. DO NOT EDIT.

package closedtsf

import (
	"syscall"
	"unsafe"
)

type TF_PRESERVEDKEY struct {
	UVKey      uint32
	UModifiers uint32
}

// AA80E801-2021-11D2-93E0-0060B067B86E
var IID_ITfThreadMgr = syscall.GUID{Data1: 0xAA80E801, Data2: 0x2021, Data3: 0x11D2, Data4: [8]byte{0x93, 0xE0, 0x00, 0x60, 0xB0, 0x67, 0xB8, 0x6E}}

type ITfThreadMgrInterface interface {
	IUnknownInterface
	Activate(ptid *uint32) HRESULT
	Deactivate() HRESULT
	CreateDocumentMgr(ppdim **ITfDocumentMgr) HRESULT
	EnumDocumentMgrs(ppEnum **IEnumTfDocumentMgrs) HRESULT
	GetFocus(ppdimFocus **ITfDocumentMgr) HRESULT
	SetFocus(pdimFocus *ITfDocumentMgr) HRESULT
	AssociateFocus(hwnd HWND, pdimNew *ITfDocumentMgr, ppdimPrev **ITfDocumentMgr) HRESULT
	IsThreadFocus(pfThreadFocus *BOOL) HRESULT
	GetFunctionProvider(clsid *syscall.GUID, ppFuncProv **ITfFunctionProvider) HRESULT
	EnumFunctionProviders(ppEnum **IEnumTfFunctionProviders) HRESULT
	GetGlobalCompartment(ppCompMgr **ITfCompartmentMgr) HRESULT
}

type ITfThreadMgrVtbl struct {
	IUnknownVtbl
	Activate              uintptr
	Deactivate            uintptr
	CreateDocumentMgr     uintptr
	EnumDocumentMgrs      uintptr
	GetFocus              uintptr
	SetFocus              uintptr
	AssociateFocus        uintptr
	IsThreadFocus         uintptr
	GetFunctionProvider   uintptr
	EnumFunctionProviders uintptr
	GetGlobalCompartment  uintptr
}

type ITfThreadMgr struct {
	IUnknown
}

type IEnumTfDocumentMgrs struct {
	IUnknown
}

type ITfDocumentMgr struct {
	IUnknown
}

type ITfContext struct {
	IUnknown
}

// AA80E803-2021-11D2-93E0-0060B067B86E
var IID_ITfEditSession = syscall.GUID{Data1: 0xAA80E803, Data2: 0x2021, Data3: 0x11D2, Data4: [8]byte{0x93, 0xE0, 0x00, 0x60, 0xB0, 0x67, 0xB8, 0x6E}}

type ITfEditSessionInterface interface {
	IUnknownInterface
	DoEditSession(ec uint32) HRESULT
}

type ITfEditSessionVtbl struct {
	IUnknownVtbl
	DoEditSession uintptr
}

type ITfEditSession struct {
	IUnknown
}

type ITfCompartmentMgr struct {
	IUnknown
}

type ITfFunctionProvider struct {
	IUnknown
}

type IEnumTfFunctionProviders struct {
	IUnknown
}

// AA80E7F0-2021-11D2-93E0-0060B067B86E
var IID_ITfKeystrokeMgr = syscall.GUID{Data1: 0xAA80E7F0, Data2: 0x2021, Data3: 0x11D2, Data4: [8]byte{0x93, 0xE0, 0x00, 0x60, 0xB0, 0x67, 0xB8, 0x6E}}

type ITfKeystrokeMgrInterface interface {
	IUnknownInterface
	AdviseKeyEventSink(tid uint32, pSink *ITfKeyEventSink, fForeground BOOL) HRESULT
	UnadviseKeyEventSink(tid uint32) HRESULT
	GetForeground(pclsid *syscall.GUID) HRESULT
	TestKeyDown(wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	TestKeyUp(wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	KeyDown(wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	KeyUp(wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	GetPreservedKey(pic *ITfContext, pprekey *TF_PRESERVEDKEY, pguid *syscall.GUID) HRESULT
	IsPreservedKey(rguid *syscall.GUID, pprekey *TF_PRESERVEDKEY, pfRegistered *BOOL) HRESULT
	PreserveKey(tid uint32, rguid *syscall.GUID, prekey *TF_PRESERVEDKEY, pchDesc PWSTR, cchDesc uint32) HRESULT
	UnpreserveKey(rguid *syscall.GUID, pprekey *TF_PRESERVEDKEY) HRESULT
	SetPreservedKeyDescription(rguid *syscall.GUID, pchDesc PWSTR, cchDesc uint32) HRESULT
	GetPreservedKeyDescription(rguid *syscall.GUID, pbstrDesc *BSTR) HRESULT
	SimulatePreservedKey(pic *ITfContext, rguid *syscall.GUID, pfEaten *BOOL) HRESULT
}

type ITfKeystrokeMgrVtbl struct {
	IUnknownVtbl
	AdviseKeyEventSink         uintptr
	UnadviseKeyEventSink       uintptr
	GetForeground              uintptr
	TestKeyDown                uintptr
	TestKeyUp                  uintptr
	KeyDown                    uintptr
	KeyUp                      uintptr
	GetPreservedKey            uintptr
	IsPreservedKey             uintptr
	PreserveKey                uintptr
	UnpreserveKey              uintptr
	SetPreservedKeyDescription uintptr
	GetPreservedKeyDescription uintptr
	SimulatePreservedKey       uintptr
}

type ITfKeystrokeMgr struct {
	IUnknown
}

// AA80E7F5-2021-11D2-93E0-0060B067B86E
var IID_ITfKeyEventSink = syscall.GUID{Data1: 0xAA80E7F5, Data2: 0x2021, Data3: 0x11D2, Data4: [8]byte{0x93, 0xE0, 0x00, 0x60, 0xB0, 0x67, 0xB8, 0x6E}}

type ITfKeyEventSinkInterface interface {
	IUnknownInterface
	OnSetFocus(fForeground BOOL) HRESULT
	OnTestKeyDown(pic *ITfContext, wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	OnTestKeyUp(pic *ITfContext, wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	OnKeyDown(pic *ITfContext, wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	OnKeyUp(pic *ITfContext, wParam WPARAM, lParam LPARAM, pfEaten *BOOL) HRESULT
	OnPreservedKey(pic *ITfContext, rguid *syscall.GUID, pfEaten *BOOL) HRESULT
}

type ITfKeyEventSinkVtbl struct {
	IUnknownVtbl
	OnSetFocus     uintptr
	OnTestKeyDown  uintptr
	OnTestKeyUp    uintptr
	OnKeyDown      uintptr
	OnKeyUp        uintptr
	OnPreservedKey uintptr
}

type ITfKeyEventSink struct {
	IUnknown
}

// AA80E7F7-2021-11D2-93E0-0060B067B86E
var IID_ITfTextInputProcessor = syscall.GUID{Data1: 0xAA80E7F7, Data2: 0x2021, Data3: 0x11D2, Data4: [8]byte{0x93, 0xE0, 0x00, 0x60, 0xB0, 0x67, 0xB8, 0x6E}}

type ITfTextInputProcessorInterface interface {
	IUnknownInterface
	Activate(ptim *ITfThreadMgr, tid uint32) HRESULT
	Deactivate() HRESULT
}

type ITfTextInputProcessorVtbl struct {
	IUnknownVtbl
	Activate   uintptr
	Deactivate uintptr
}

type ITfTextInputProcessor struct {
	IUnknown
}
type BOOL = int32

type BSTR = *uint16

type HRESULT = int32
type HWND = uintptr
type LPARAM = uintptr

type PWSTR = *uint16
type WPARAM = uintptr

type IUnknownInterface interface {
	QueryInterface(riid *syscall.GUID, ppvObject unsafe.Pointer) HRESULT
	AddRef() uint32
	Release() uint32
}

type IUnknownVtbl struct {
	QueryInterface uintptr
	AddRef         uintptr
	Release        uintptr
}

type IUnknown struct {
	LpVtbl *[1024]uintptr
}
